import React from 'react';
import Head from 'next/head';

const CLPHead = () => {
  return (
    <Head>
      <title></title>
      <meta name="description" content="Generated by create next app" />
      <link rel="preconnect" href="https://fonts.googleapis.com" />
      <link rel="preconnect" href="https://fonts.gstatic.com" />
    </Head>
  );
};

export default CLPHead;
